### ISSUE TITLE
Can't figure out how to run

### ISSUE THREAD

**Issue by team4music** [shallowdream204/DreamClear#1]
First of all your project seems to be very interesting, but sadly i wasn't able to get it run.

I placed config.json and diffusion_pytorch_model.bin in the correct folders but if i do so he demands a safetensor file. I was able to find the diffusion_pytorch_model.safetensors but if i use that i get a bunch of issues. So i'm a bit stuck in here.

**Comment by shallowdream204** [comment]
Oh, I haven’t encountered this issue. I use the [vae](https://huggingface.co/PixArt-alpha/PixArt-alpha/tree/main/sd-vae-ft-ema) provided by pixart-α repo. But maybe you could download the safetensors file from the [official hf repo](https://huggingface.co/stabilityai/sd-vae-ft-ema/tree/main) of sd-vae-ft-ema.
