### ISSUE TITLE
problem when try to pip3 install -r requirements.txt ERROR

### ISSUE THREAD

**Issue by SNAKEIX** [shallowdream204/DreamClear#11]
pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

i did everything right in all steps until i reach this one , how to fix it

**Comment by PixelArmony** [comment]
Hello SNAKEIX,

I am not affiliated with the DreamClear project, but first, you need to create a directory where you have all your AI stuff (e.g., "AI-Projects"). Then, follow these steps via a prompt window. This will automatically create a folder called "Dreamclear" inside your "AI-Projects" directory:
```
git clone https://github.com/shallowdream204/DreamClear.git
cd DreamClear
```
Now, you need to create a Conda environment. These commands create a new Conda environment named **dreamclear** with Python 3.9 installed. (The -y flag automatically confirms the creation without asking for user input). The _conda activate dreamclear_ command activates the newly created dreamclear environment so you can use it to install and run your software.
```
conda create -n dreamclear python=3.9 -y
conda activate dreamclear
```
Now, open your **dreamclear** folder and ensure the **requirements.txt** file is present. Then type this command in the prompt:

`pip3 install -r requirements.txt`

After that, all you need to do is to download all the models and the **sd-vae-ft-ema** and **t5-v1_1-xxl** folders, here:
[https://huggingface.co/shallowdream204/DreamClear/tree/main](https://huggingface.co/shallowdream204/DreamClear/tree/main)

Put them all in your **models** directory that you'll need to create (e.g., C:\AI-Projects\Dreamclear\models), and you are ready to go! Remember: don't forget to activate your Conda environment first each time you want to use Dreamclear!

NOTE: If you have get a PIP error during the installation, click on this link to fix it:
[https://github.com/shallowdream204/DreamClear/issues/10#issue-2631376498](https://github.com/shallowdream204/DreamClear/issues/10#issue-2631376498)
—
Hope this helps! Good luck and have fun!

**Comment by SNAKEIX** [comment]
thank you it works :D , but now how i start the upscaler

**Comment by PixelArmony** [comment]
Hey SNAKEIX,

I'm running into issues with DreamClear for image restoration. There are multiple problems, including deprecation warnings and initialization errors due to unexpected keyword arguments like "even_batches". I'll create a new topic to ask the developers for assistance. In the meantime, keep your downloaded models handy; you'll need them once the devs fix this issue!
