### ISSUE TITLE
Question: can somehow be used on Android, stand-alone?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [shallowdream204/DreamClear#12]
Is there any way to have a mini-app that all it does is to enhance images, using this repository?
If so, how can I do it? Any fork/port of it for Android, as a library?

**Comment by shallowdream204** [comment]
Sorry, I'm not familiar with the Android system.

**Comment by AndroidDeveloperLB** [comment]
@shallowdream204 Well, if you can port it to Java/Kotlin or use C/C++ and have some bridge to it via Java/Kotlin. It should have no UI elements at all (because Android uses its own UI framework, not having anything of PC) and use only core stuff. Then it should be possible to be used on Android.
But, on Android you have to be extra careful with memory usage. Not all devices out there have plenty of memory.
