### ISSUE TITLE
inference on my own data

### ISSUE THREAD

**Issue by milely** [shallowdream204/DreamClear#15]
Thanks for the great work. I hope to perform inference on my own data. Is there a complete pipeline?

**Comment by shallowdream204** [comment]
Thanks for your appreciation. Refer to Issue https://github.com/shallowdream204/DreamClear/issues/9.

**Comment by shallowdream204** [comment]
We have released more user-friendly [inference code](https://github.com/shallowdream204/DreamClear?tab=readme-ov-file#-inference). Feel free to test your own images!
