### ISSUE TITLE
Question regarding the use of LLaVa 

### ISSUE THREAD

**Issue by SkaarFacee** [shallowdream204/DreamClear#19]
I went through the paper and noticed that you mentioned using Gemini 1.5 Pro as the MLLM for generating text prompts. However, under the architecture section, you also suggested using LLaVa. I’m curious to know if that was a mistake or if you had used them both. Let me know what you think!

**Comment by shallowdream204** [comment]
This is not an error. We only used Gemini in the data generation phase. However, in constructing the DreamClear model, we used LLaVA, an effective open-source MLLM. We did not use Gemini in DreamClear because it is not open-source.

**Comment by SkaarFacee** [comment]
Oh okay. Thanks for the clarification. Are you planning on making the dataset public soon ?
