### ISSUE TITLE
Prospective Collaboration For Video Restoration

### ISSUE THREAD

**Issue by honestabelink** [shallowdream204/DreamClear#20]
Hi DreamClear Team,

Thanks for your contribution to open source!!!

We are looking to commission a custom model for video degradation. Will you consider such a collaboration?
We can provide data, 1M+ video and compute GH200's. Our data is HQ and focuses only on human subject, diverse in age, gender, ethnicity.

Main Goal:
Local Blur - local object blur while the scene is HQ, usually found in our video when humans move their body (hands, feet, face).
Global Blur - camera motion, whole scene blur

Secondary:
Over/Under-exposure and other typical degradation (low res, noise, etc).

Thanks for your time.

**Comment by SkaarFacee** [comment]
If it is possible, I would like to be a part of this team. Please let me know if you need any of my details to be sent in an official email

**Comment by honestabelink** [comment]
Hi @SkaarFacee ,

Thanks for your consideration!

You can reach me directly at honestabelink@openroot-compute.org

**Comment by shallowdream204** [comment]
Thank you for your recognition. We currently do not have plans to develop a video restoration model.
