### ISSUE TITLE
图片是黑色的，哪里出错了？

### ISSUE THREAD

**Issue by ningbende** [shallowdream204/DreamClear#22]
您好，请教用官方的推理代码
图片是黑色的，哪里出错了？
![image](https://github.com/user-attachments/assets/2cbd18ce-8f1f-4ef6-9b4e-fb1050b42690)

推理过程：
python3 -m torch.distributed.launch --nproc_per_node 1 --master_port 1234 \
    test.py configs/DreamClear/DreamClear_Test.py \
    --dreamclear_ckpt pretrained/DreamClear-1024.pth \
    --swinir_ckpt pretrained/general_swinir_v1.ckpt \
    --vae_ckpt pretrained/sd-vae-ft-ema/PixArt-alpha \
    --t5_ckpt t5-v1_1-xxl \
    --llava_ckpt llava-v1.6-vicuna-13b \
    --lre --cfg_scale 4.5 --color_align wavelet \
    --image_path RealLQ250/lq \
    --save_dir validation \
    --mixed_precision fp16 \
    --upscale 4
log：

/root/anaconda3/envs/py39torch2/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:1234 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [localhost]:1234 (errno: 97 - Address family not supported by protocol).
/root/anaconda3/envs/py39torch2/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [localhost]:1234 (errno: 97 - Address family not supported by protocol).
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-12-03 03:36:30,678 - PixArt - INFO - Initializing: DDP for inference
2024-12-03 03:36:39,451 - PixArt - WARNING - lewei scale: (2.0,), base size: 64
2024-12-03 03:36:51,819 - PixArt - INFO - Using fp16 inference for DiT.
2024-12-03 03:36:51,828 - PixArt - INFO - ControlPixArtMSHalfSR2Branch Model Parameters: 2,211,876,212
2024-12-03 03:36:51,831 - PixArt - INFO - T5 max token length: 120
2024-12-03 03:36:59,942 - PixArt - INFO - Load checkpoint from pretrained/DreamClear-1024.pth. Load ema: False.
2024-12-03 03:37:00,184 - PixArt - WARNING - Missing keys: ['base_model.pos_embed']
2024-12-03 03:37:00,184 - PixArt - WARNING - Unexpected keys: []
t5-v1_1-xxl/
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Some weights of T5EncoderModel were not initialized from the model checkpoint at t5-v1_1-xxl/ and are newly initialized: ['encoder.block.11.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.11.layer.1.DenseReluDense.wo.weight', 'encoder.block.11.layer.1.layer_norm.weight', 'encoder.block.12.layer.0.SelfAttention.k.weight', 'encoder.block.12.layer.0.SelfAttention.o.weight', 'encoder.block.12.layer.0.SelfAttention.q.weight', 'encoder.block.12.layer.0.SelfAttention.v.weight', 'encoder.block.12.layer.0.layer_norm.weight', 'encoder.block.12.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.12.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.12.layer.1.DenseReluDense.wo.weight', 'encoder.block.12.layer.1.layer_norm.weight', 'encoder.block.13.layer.0.SelfAttention.k.weight', 'encoder.block.13.layer.0.SelfAttention.o.weight', 'encoder.block.13.layer.0.SelfAttention.q.weight', 'encoder.block.13.layer.0.SelfAttention.v.weight', 'encoder.block.13.layer.0.layer_norm.weight', 'encoder.block.13.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.13.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.13.layer.1.DenseReluDense.wo.weight', 'encoder.block.13.layer.1.layer_norm.weight', 'encoder.block.14.layer.0.SelfAttention.k.weight', 'encoder.block.14.layer.0.SelfAttention.o.weight', 'encoder.block.14.layer.0.SelfAttention.q.weight', 'encoder.block.14.layer.0.SelfAttention.v.weight', 'encoder.block.14.layer.0.layer_norm.weight', 'encoder.block.14.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.14.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.14.layer.1.DenseReluDense.wo.weight', 'encoder.block.14.layer.1.layer_norm.weight', 'encoder.block.15.layer.0.SelfAttention.k.weight', 'encoder.block.15.layer.0.SelfAttention.o.weight', 'encoder.block.15.layer.0.SelfAttention.q.weight', 'encoder.block.15.layer.0.SelfAttention.v.weight', 'encoder.block.15.layer.0.layer_norm.weight', 'encoder.block.15.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.15.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.15.layer.1.DenseReluDense.wo.weight', 'encoder.block.15.layer.1.layer_norm.weight', 'encoder.block.16.layer.0.SelfAttention.k.weight', 'encoder.block.16.layer.0.SelfAttention.o.weight', 'encoder.block.16.layer.0.SelfAttention.q.weight', 'encoder.block.16.layer.0.SelfAttention.v.weight', 'encoder.block.16.layer.0.layer_norm.weight', 'encoder.block.16.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.16.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.16.layer.1.DenseReluDense.wo.weight', 'encoder.block.16.layer.1.layer_norm.weight', 'encoder.block.17.layer.0.SelfAttention.k.weight', 'encoder.block.17.layer.0.SelfAttention.o.weight', 'encoder.block.17.layer.0.SelfAttention.q.weight', 'encoder.block.17.layer.0.SelfAttention.v.weight', 'encoder.block.17.layer.0.layer_norm.weight', 'encoder.block.17.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.17.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.17.layer.1.DenseReluDense.wo.weight', 'encoder.block.17.layer.1.layer_norm.weight', 'encoder.block.18.layer.0.SelfAttention.k.weight', 'encoder.block.18.layer.0.SelfAttention.o.weight', 'encoder.block.18.layer.0.SelfAttention.q.weight', 'encoder.block.18.layer.0.SelfAttention.v.weight', 'encoder.block.18.layer.0.layer_norm.weight', 'encoder.block.18.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.18.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.18.layer.1.DenseReluDense.wo.weight', 'encoder.block.18.layer.1.layer_norm.weight', 'encoder.block.19.layer.0.SelfAttention.k.weight', 'encoder.block.19.layer.0.SelfAttention.o.weight', 'encoder.block.19.layer.0.SelfAttention.q.weight', 'encoder.block.19.layer.0.SelfAttention.v.weight', 'encoder.block.19.layer.0.layer_norm.weight', 'encoder.block.19.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.19.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.19.layer.1.DenseReluDense.wo.weight', 'encoder.block.19.layer.1.layer_norm.weight', 'encoder.block.20.layer.0.SelfAttention.k.weight', 'encoder.block.20.layer.0.SelfAttention.o.weight', 'encoder.block.20.layer.0.SelfAttention.q.weight', 'encoder.block.20.layer.0.SelfAttention.v.weight', 'encoder.block.20.layer.0.layer_norm.weight', 'encoder.block.20.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.20.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.20.layer.1.DenseReluDense.wo.weight', 'encoder.block.20.layer.1.layer_norm.weight', 'encoder.block.21.layer.0.SelfAttention.k.weight', 'encoder.block.21.layer.0.SelfAttention.o.weight', 'encoder.block.21.layer.0.SelfAttention.q.weight', 'encoder.block.21.layer.0.SelfAttention.v.weight', 'encoder.block.21.layer.0.layer_norm.weight', 'encoder.block.21.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.21.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.21.layer.1.DenseReluDense.wo.weight', 'encoder.block.21.layer.1.layer_norm.weight', 'encoder.block.22.layer.0.SelfAttention.k.weight', 'encoder.block.22.layer.0.SelfAttention.o.weight', 'encoder.block.22.layer.0.SelfAttention.q.weight', 'encoder.block.22.layer.0.SelfAttention.v.weight', 'encoder.block.22.layer.0.layer_norm.weight', 'encoder.block.22.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.22.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.22.layer.1.DenseReluDense.wo.weight', 'encoder.block.22.layer.1.layer_norm.weight', 'encoder.block.23.layer.0.SelfAttention.k.weight', 'encoder.block.23.layer.0.SelfAttention.o.weight', 'encoder.block.23.layer.0.SelfAttention.q.weight', 'encoder.block.23.layer.0.SelfAttention.v.weight', 'encoder.block.23.layer.0.layer_norm.weight', 'encoder.block.23.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.23.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.23.layer.1.DenseReluDense.wo.weight', 'encoder.block.23.layer.1.layer_norm.weight', 'encoder.final_layer_norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:10<00:00,  1.73s/it]
The image is a digital artwork featuring a character with a fantasy theme. The character has a prominent, stylized appearance with a humanoid form, but with distinct non-human features. The character has a furry, ape-like face with a prominent brow ridge, a pronounced nose, and a somewhat aggressive expression. The hair is spiky and appears to be a mix of blond and gray, with some areas appearing to be styled to resemble a mane.  The character is wearing armor that has a rich, ornate design, suggesting a high-ranking status or a warrior role. The armor is predominantly gold and bronze, with intricate patterns and designs that give it an ancient or regal look. The armor pieces include a breastplate, shoulder guards, and what appears to be a helmet or headpiece with a crest or plume.  The background is dark and moody, with a blurred, almost gothic-looking architecture that adds to the fantastical atmosphere of the image. The overall style of the image is realistic with a fantasy twist, aiming to create a sense of drama and intensity. The lighting and shadows are carefully crafted to highlight the character's features and the intricate details of the armor.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:25<00:00,  1.71s/it]
The image depicts a serene natural landscape. In the foreground, there is a tranquil body of water reflecting the surrounding scenery. The water's surface is calm, and the reflections are clear, suggesting a still day. On the left side of the image, there is a grassy area with a few small birds scattered across it. The birds appear to be resting or foraging.  In the middle ground, there is a bridge with a curved arch that spans across the water. The bridge has a classic design, with a stone or concrete structure that contrasts with the natural elements. The bridge is partially obscured by the foliage of trees, which are in autumn colors, with shades of orange, yellow, and green. The trees are lush and dense, indicating a healthy and thriving environment.  The background features a clear blue sky with no visible clouds, suggesting a sunny day. The overall style of the image is a realistic photograph with a focus on natural beauty and tranquility. The colors are vibrant, with the autumnal hues of the trees providing a warm contrast to the cool blue of the sky and water. There are no visible texts or human-made structures that distract from the natural setting. The image captures a moment of peacefulness and the quiet charm of a natural landscape.
 38%|████████████████████████████████████████████████████████████████▏

**Comment by shallowdream204** [comment]
我刚刚测试了一下代码可以正常inference，看一下是不是下载的ckpt出了问题？比如VAE？
```shell
python3 -m torch.distributed.launch --nproc_per_node 1 --master_port 1234 \
    test.py configs/DreamClear/DreamClear_Test.py \
    --dreamclear_ckpt /mnt/bn/yiren-bytenas2/yuang.ai/exp/pixart/ckpt/DreamClear-1024.pth \
    --swinir_ckpt /mnt/bn/yiren-bytenas2/yuang.ai/exp/pixart/ckpt/general_swinir_v1.ckpt \
    --vae_ckpt /mnt/bn/yiren-bytenas2/yuang.ai/exp/pixart/ckpt/sd-vae-ft-ema \
    --t5_ckpt /mnt/bn/yiren-bytenas2/yuang.ai/exp/pixart/ckpt/t5-v1_1-xxl \
    --llava_ckpt liuhaotian/llava-v1.6-vicuna-13b \
    --lre --cfg_scale 4.5 --color_align wavelet \
    --image_path /mnt/bn/yiren-bytenas2/yuang.ai/data/sr/aya_nips24/benchmark/RealLQ250/lq \
    --save_dir validation \
    --mixed_precision fp16 \
    --upscale 4
 ```

**Comment by shallowdream204** [comment]
看起来T5的ckpt没有正确读取 @ningbende

**Comment by ningbende** [comment]
我重新更改，感谢及时的回复！再次感谢！

**Comment by thisisqiaoqiao** [comment]
请问您解决了嘛？

**Comment by thisisqiaoqiao** [comment]
2025-08-14 15:49:00,993 - PixArt - INFO - Initializing: DDP for inference
2025-08-14 15:49:07,701 - PixArt - WARNING - lewei scale: (2.0,), base size: 32
2025-08-14 15:49:16,564 - PixArt - INFO - Using fp16 inference for DiT.
2025-08-14 15:49:16,570 - PixArt - INFO - ControlPixArtMSHalfSR2Branch Model Parameters: 2,211,876,212
2025-08-14 15:49:16,570 - PixArt - INFO - T5 max token length: 120
2025-08-14 15:49:22,157 - PixArt - INFO - Load checkpoint from DreamClear-main/weight/DreamClear-1024.pth. Load ema: False.
2025-08-14 15:49:22,483 - PixArt - WARNING - Missing keys: ['base_model.pos_embed']
2025-08-14 15:49:22,484 - PixArt - WARNING - Unexpected keys: []
/weight/t5-v1_1-xxl/
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.10s/it]
load_8bit---------------------------------------------------------------------
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
__init__-------------------------------------------------------------------------------------
self.vision_tower_name：  /weight/clip-vit-large-patch14-336
__init__-------------------------------------------------------------------------------------
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.36s/it]
The image is a black and white photograph that captures a scene of a tree with bare branches. The tree is positioned in the foreground, with its branches extending towards the top of the frame. The background is filled with a dense cluster of trees, creating a sense of depth and perspective. The style of the image is reminiscent of a traditional black and white photograph, with a focus on the contrast between the tree in the foreground and the background. The lack of color adds a timeless quality to the image, emphasizing the shapes and textures within the scene.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:00<00:00,  1.20s/it]
The R&shereenvelope 111 moresult 10-not to 20-not Valley of a 11t 1, Trent v. The R&bacroof, Sea H3820-like  dead-like 29ineu290-like 2 machine of death: The R”>
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:31<00:00,  1.59it/s]
The R”>
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:31<00:00,  1.59it/s]

**Comment by thisisqiaoqiao** [comment]
2025-08-14 15:49:00,993 - PixArt - INFO - Initializing: DDP for inference
2025-08-14 15:49:07,701 - PixArt - WARNING - lewei scale: (2.0,), base size: 32
2025-08-14 15:49:16,564 - PixArt - INFO - Using fp16 inference for DiT.
2025-08-14 15:49:16,570 - PixArt - INFO - ControlPixArtMSHalfSR2Branch Model Parameters: 2,211,876,212
2025-08-14 15:49:16,570 - PixArt - INFO - T5 max token length: 120
2025-08-14 15:49:22,157 - PixArt - INFO - Load checkpoint from DreamClear-main/weight/DreamClear-1024.pth. Load ema: False.
2025-08-14 15:49:22,483 - PixArt - WARNING - Missing keys: ['base_model.pos_embed']
2025-08-14 15:49:22,484 - PixArt - WARNING - Unexpected keys: []
/weight/t5-v1_1-xxl/
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the legacy (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set legacy=False. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in huggingface/transformers#24565
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00, 5.10s/it]
load_8bit---------------------------------------------------------------------
The load_in_4bit and load_in_8bit arguments are deprecated and will be removed in the future versions. Please, pass a BitsAndBytesConfig object in quantization_config argument instead.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
init-------------------------------------------------------------------------------------
self.vision_tower_name： /weight/clip-vit-large-patch14-336
init-------------------------------------------------------------------------------------
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00, 1.36s/it]
The image is a black and white photograph that captures a scene of a tree with bare branches. The tree is positioned in the foreground, with its branches extending towards the top of the frame. The background is filled with a dense cluster of trees, creating a sense of depth and perspective. The style of the image is reminiscent of a traditional black and white photograph, with a focus on the contrast between the tree in the foreground and the background. The lack of color adds a timeless quality to the image, emphasizing the shapes and textures within the scene.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:00<00:00, 1.20s/it]
The R&shereenvelope 111 moresult 10-not to 20-not Valley of a 11t 1, Trent v. The R&bacroof, Sea H3820-like dead-like 29ineu290-like 2 machine of death: The R”>
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:31<00:00, 1.59it/s]
The R”>
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:31<00:00, 1.59it/s]

我出现了一样的情况，发现在经过扩散后，值变成了nan
