### ISSUE TITLE
How does it compare to ControlNet tile upscale?

### ISSUE THREAD

**Issue by Sanster** [shallowdream204/DreamClear#3]
Thank you for your open-source model! From Figure 5: User study in the paper, it seems that the results are really impressive. I have a question: will the specially trained DiT-based image restoration model perform much better than the ControlNet tile upscale (e.g., https://github.com/ssitu/ComfyUI_UltimateSDUpscale)? Another question is whether DreamClear can generate images at 2k or even 4k resolution? Thanks

**Comment by shallowdream204** [comment]
Thanks for your appreciation. I'll try to compare DreamClear with ControlNet tile upscale next month.
Since DreamClear is based on pixart-α-1024, it may not be able to directly generate 2K or 4K images. Using the tile approach might alleviate this issue.
