### ISSUE TITLE
Pytorch 2.1.1 is absolutely required? Re: Old + doesn't support 12.1+ CUDA

### ISSUE THREAD

**Issue by CCpt5** [shallowdream204/DreamClear#6]
Hello! Thanks for your work on this project! 

I tried installing yesterday (and took another look today) and since it requires pytorch 2.1.1 I'm limited in my options. Pytorch is already up to version 2.5, and 2.1 doesn't support CUDA after 12.1 (currently they're up to ~12.6).

Was curious if this is essential or if there's a chance a future version may allow for newer versions of pytorch.

On the other hand, if there's a demo somewhere just to test that'd be great also (Huggingface/etc).

Thanks again for your work!

**Comment by shallowdream204** [comment]
Thank you for your interest. Our environment is consistent with [PixArt-Alpha](https://github.com/PixArt-alpha/PixArt-alpha), and we have not yet tested whether higher versions of PyTorch might cause compatibility issues.
