### ISSUE TITLE
What is NPZ File?

### ISSUE THREAD

**Issue by stormcenter** [shallowdream204/DreamClear#8]
How  it can be generated, if I  choose a random pic

**Comment by shallowdream204** [comment]
Oh, the npz file is the text features extracted by T5. The example code is [here](https://github.com/shallowdream204/DreamClear/blob/main/tools/extract_t5_features.py). I'll update more convenient code for obtaining text prompts and features soon.

**Comment by lissettecarlr** [comment]
I see, so if you want to use your own images, you first need to use T5 to extract features, and then input  the images along with the features for inference。

**Comment by ningbende** [comment]
hi， in the example code "extract_t5_features.py", what is caption files? how to generate?

**Comment by shallowdream204** [comment]
We have released more user-friendly [inference code](https://github.com/shallowdream204/DreamClear?tab=readme-ov-file#-inference). Feel free to test your own images!
