### ISSUE TITLE
how to test my own data?

### ISSUE THREAD

**Issue by ningbende** [shallowdream204/DreamClear#9]
Thanks for your great job
I wander how to test my own data

**Comment by milely** [comment]
Hi, have you successfully performed inference on your data?

**Comment by ningbende** [comment]
nope

**Comment by shallowdream204** [comment]
Regarding how to test your own data: the inference code in the current codebase hasn't been updated yet to include the process of extracting text prompts and T5 features. I'll update this part as soon as possible—it's currently a busy time with the CVPR deadline approaching. Thank you all for your patience and understanding!

**Comment by shallowdream204** [comment]
We have released more user-friendly [inference code](https://github.com/shallowdream204/DreamClear?tab=readme-ov-file#-inference). Feel free to test your own images!
